import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar/NavBar";
import CounterProvider from "@/providers/CounterProvider/CounterProvider";
import AuthProvider from "@/providers/AuthProvider/AuthProvider";

export const metadata: Metadata = {
  title: "Minha loja virtual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <AuthProvider>
          <CounterProvider>
            <NavBar />
            <div className="container mx-auto">
              {children}
            </div>
          </CounterProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
